version=0.1

[[datasets]]

  key="hall_2012"

  [datasets.publication]
    doi= "10.1109/TSE.2011.103"
    openalex= "W2151666086"

  [datasets.data]
        doi="10.5281/zenodo.1162952"

  [datasets.scripts]


[[datasets]]
  # Processes 1 dataset (https://osf.io/tnxju/)

  key="Donners_2021"

  [datasets.publication]

  doi= "10.1007/s40262-021-01042-w"
  openalex= "W3187789458"

  [datasets.data]

  doi="https://osf.io/tnxju/"

  [datasets.scripts]


[[datasets]]

  key="Meijboom_2022"

  [datasets.publication]

  doi= "10.1007/s40259-021-00508-4"
  openalex= "W4200279042"

  [datasets.data]

  doi="https://osf.io/4cdku/"

  [datasets.scripts]

[[datasets]]

  key="Valk_2021"

  [datasets.publication]

  doi= "10.1111/obr.13376"
  openalex= "W3216502150"

  [datasets.data]

  doi="https://osf.io/download/gmjcv/"

  [datasets.scripts]


[[datasets]]

  key="Smid_2020"

  [datasets.publication]

  doi= "10.1080/10705511.2019.1577140"
  openalex= "W2944958851"

  [datasets.data]

  doi="https://osf.io/gxams"

  [datasets.scripts]


[[datasets]]

  key="Brouwer_2019"

  [datasets.publication]

  doi= "10.1016/j.cpr.2019.101773"
  openalex= "W2985119860"

  [datasets.data]

  doi="https://osf.io/py7ek"

  [datasets.scripts]

[[datasets]]

  key="Appenzeller-Herzog_2020"

  [datasets.publication]

  doi= "10.1111/liv.14179"
  openalex= "W2949422680"

  [datasets.data]

  doi="https://doi.org/10.5281/zenodo.3625931"

  [datasets.scripts]


[[datasets]]

  # original study https://doi.org/10.1002/ebm2.24

  key="Bannach-Brown_2019"

  [datasets.publication]

  doi= "10.1186/s13643-019-0942-7"
  openalex= "W2910642642"

  [datasets.data]

  doi="https://doi.org/10.5281/zenodo.151190"

  [datasets.scripts]


[[datasets]]

  key="Bos_2018"

  [datasets.publication]

  doi= "10.1016/j.jalz.2018.04.007"
  openalex= "W2804868354"

  [datasets.data]

  doi="https://osf.io/w3kbq/"

  [datasets.scripts]


[[datasets]]

  key="Cohen_2006_ACEInhibitors"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py ACEInhibitors"

[[datasets]]

  key="Cohen_2006_CalciumChannelBlockers"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py CalciumChannelBlockers"


[[datasets]]

  key="Cohen_2006_ProtonPumpInhibitors"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py ProtonPumpInhibitors"


[[datasets]]

  key="Cohen_2006_ADHD"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py ADHD"

[[datasets]]

  key="Cohen_2006_Estrogens"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py Estrogens"


[[datasets]]

  key="Cohen_2006_SkeletalMuscleRelaxants"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py SkeletalMuscleRelaxants"



[[datasets]]

  key="Cohen_2006_Antihistamines"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py Antihistamines"

[[datasets]]

  key="Cohen_2006_NSAIDS"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py NSAIDS"


[[datasets]]

  key="Cohen_2006_Statins"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py Statins"



[[datasets]]

  key="Cohen_2006_AtypicalAntipsychotics"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py AtypicalAntipsychotics"

[[datasets]]

  key="Cohen_2006_Opioids"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py Opioids"


[[datasets]]

  key="Cohen_2006_Triptans"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py Triptans"



[[datasets]]

  key="Cohen_2006_BetaBlockers"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py BetaBlockers"

[[datasets]]

  key="Cohen_2006_OralHypoglycemics"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py OralHypoglycemics"


[[datasets]]

  key="Cohen_2006_UrinaryIncontinence"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"
  openalex= "W168362576"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py UrinaryIncontinence"

