version=0.1



[[datasets]]

  # Part of Yu et al. 2018 https://doi.org/10.1007/s10664-017-9587-0

  key="hall_2012"

  [datasets.publication]
  doi= "10.1109/TSE.2011.103"

  [datasets.data]
  doi="10.5281/zenodo.1162952"


[[datasets]]

  # Part of Yu et al. 2018 https://doi.org/10.1007/s10664-017-9587-0

  key="Wahono_2015"

  [datasets.publication]
  # http://journal.ilmukomputer.org/index.php?journal=jse&page=article&op=view&path%5B%5D=47
  doi= ""

  [datasets.data]
  doi="10.5281/zenodo.1162952"


[[datasets]]

  # Part of Yu et al. 2018 https://doi.org/10.1007/s10664-017-9587-0

  key="Radjenovic_2013"

  [datasets.publication]
  doi= "10.1016/j.infsof.2013.02.009"

  [datasets.data]
  doi="10.5281/zenodo.1162952"


[[datasets]]

  # Part of Yu et al. 2018 https://doi.org/10.1007/s10664-017-9587-0

  key="Kitchenham_2010"

  [datasets.publication]
  doi= "10.1016/j.infsof.2010.03.006"

  [datasets.data]
  doi="10.5281/zenodo.1162952"

[[datasets]]
  # Processes 1 dataset (https://osf.io/tnxju/)

  key="Donners_2021"

  [datasets.publication]

  doi= "10.1007/s40262-021-01042-w"

  [datasets.data]

  doi="https://osf.io/tnxju/"

[[datasets]]

  key="Meijboom_2022"

  [datasets.publication]

  doi= "10.1007/s40259-021-00508-4"

  [datasets.data]

  doi="https://osf.io/4cdku/"
[[datasets]]

  key="Valk_2021"

  [datasets.publication]

  doi= "10.1111/obr.13376"

  [datasets.data]

  doi="https://osf.io/download/gmjcv/"

[[datasets]]

  key="Smid_2020"

  [datasets.publication]

  doi= "10.1080/10705511.2019.1577140"

  [datasets.data]

  doi="https://osf.io/gxams"

[[datasets]]

  key="Brouwer_2019"

  [datasets.publication]

  doi= "10.1016/j.cpr.2019.101773"

  [datasets.data]

  doi="https://osf.io/py7ek"
[[datasets]]

  key="Appenzeller-Herzog_2020"

  [datasets.publication]

  doi= "10.1111/liv.14179"

  [datasets.data]

  doi="https://doi.org/10.5281/zenodo.3625931"

[[datasets]]

  # original study https://doi.org/10.1002/ebm2.24

  key="Bannach-Brown_2019"

  [datasets.publication]

  doi= "10.1186/s13643-019-0942-7"

  [datasets.data]

  doi="https://doi.org/10.5281/zenodo.151190"

[[datasets]]

  key="Bos_2018"

  [datasets.publication]

  doi= "10.1016/j.jalz.2018.04.007"

  [datasets.data]

  doi="https://osf.io/w3kbq/"

[[datasets]]

  key="Cohen_2006_ACEInhibitors"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py ACEInhibitors"

[[datasets]]

  key="Cohen_2006_CalciumChannelBlockers"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py CalciumChannelBlockers"


[[datasets]]

  key="Cohen_2006_ProtonPumpInhibitors"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py ProtonPumpInhibitors"


[[datasets]]

  key="Cohen_2006_ADHD"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py ADHD"

[[datasets]]

  key="Cohen_2006_Estrogens"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py Estrogens"


[[datasets]]

  key="Cohen_2006_SkeletalMuscleRelaxants"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py SkeletalMuscleRelaxants"



[[datasets]]

  key="Cohen_2006_Antihistamines"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py Antihistamines"

[[datasets]]

  key="Cohen_2006_NSAIDS"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py NSAIDS"


[[datasets]]

  key="Cohen_2006_Statins"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py Statins"



[[datasets]]

  key="Cohen_2006_AtypicalAntipsychotics"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py AtypicalAntipsychotics"

[[datasets]]

  key="Cohen_2006_Opioids"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py Opioids"


[[datasets]]

  key="Cohen_2006_Triptans"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py Triptans"



[[datasets]]

  key="Cohen_2006_BetaBlockers"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py BetaBlockers"

[[datasets]]

  key="Cohen_2006_OralHypoglycemics"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py OralHypoglycemics"


[[datasets]]

  key="Cohen_2006_UrinaryIncontinence"

  [datasets.publication]

  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="datasets/Cohen_2006/compose.py UrinaryIncontinence"

[[datasets]]

  key="Nagtegaal_2019"

  [datasets.publication]

  doi= "10.30636/jbpa.22.71"

  [datasets.data]

  doi="https://doi.org/10.7910/DVN/WMGPGZ/HY6N2S"


[[datasets]]

  # Note that this dataset is also used for another systematic review:
  # https://doi.org/10.1080/00273171.2017.1412293

  key="van_de_Schoot_2017"

  [datasets.publication]

  doi= "10.1080/10705511.2016.1247646"

  [datasets.data]

  doi="https://doi.org/10.17605/OSF.IO/VW3T7"


[[datasets]]

  key="van_Dis_2020"

  [datasets.publication]

  doi= "10.1001/jamapsychiatry.2019.3986"

  [datasets.data]

  doi="https://osf.io/4d9tu/"


[[datasets]]

  key="Wolters_2018"

  [datasets.publication]

  doi= "10.1016/j.jalz.2018.01.007"

  [datasets.data]

  doi="https://osf.io/sxzjg/"


