version=0.1

[[datasets]]

  key="hall_2012"

  [datasets.publication]
    doi= "10.1109/TSE.2011.103"
    openalex= "W2151666086"

  [datasets.data]
        doi="10.5281/zenodo.1162952"

  [datasets.scripts]


[[datasets]]
  # Processes 1 dataset (https://osf.io/tnxju/)

  key="Donners_2021"

  [datasets.publication]

  doi= "10.1007/s40262-021-01042-w"
  openalex= "W3187789458"

  [datasets.data]

  doi="https://osf.io/tnxju/"

  [datasets.scripts]


[[datasets]]

  key="Meijboom_2022"

  [datasets.publication]

  doi= "10.1007/s40259-021-00508-4"
  openalex= "W4200279042"

  [datasets.data]

  doi="https://osf.io/4cdku/"

  [datasets.scripts]

[[datasets]]

  key="Valk_2021"

  [datasets.publication]

  doi= "10.1111/obr.13376"
  openalex= "W3216502150"

  [datasets.data]

  doi="https://osf.io/download/gmjcv/"

  [datasets.scripts]


[[datasets]]

  key="Smid_2020"

  [datasets.publication]

  doi= "10.1080/10705511.2019.1577140"
  openalex= "W2944958851"

  [datasets.data]

  doi="https://osf.io/gxams"

  [datasets.scripts]


[[datasets]]

  key="Brouwer_2019"

  [datasets.publication]

  doi= "10.1016/j.cpr.2019.101773"
  openalex= "W2985119860"

  [datasets.data]

  doi="https://osf.io/py7ek"

  [datasets.scripts]

[[datasets]]

  key="Appenzeller-Herzog_2020"

  [datasets.publication]

  doi= "10.1111/liv.14179"
  openalex= "W2949422680"

  [datasets.data]

  doi="https://doi.org/10.5281/zenodo.3625931"

  [datasets.scripts]


[[datasets]]

  # original study https://doi.org/10.1002/ebm2.24

  key="Bannach-Brown_2019"

  [datasets.publication]

  doi= "10.1186/s13643-019-0942-7"
  openalex= "W2910642642"

  [datasets.data]

  doi="https://doi.org/10.5281/zenodo.151190"

  [datasets.scripts]
